name: Build and deploy HTML app to Azure Web App - test231

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B3BFDF3F4DF4483481C0FF51FADC83D8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_674CFB0C49814512939D60A919AE9DB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A1EAC2D249C14A59B23E09F5C9F260F2 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'test231'
          slot-name: 'Production'
          package: .
